version: '3.8'

services:
  web:
    build: .
    container_name: portal_app
    ports:
      - "${HOST_PORT:-5000}:5000"
    env_file:
      - .env
    environment:
      - TZ=${TZ:-Asia/Jakarta}
    depends_on:
      - db
    volumes:
      - ./app:/app
    restart: unless-stopped
    networks:
      - portal-network
      - portal-login-sec 

  db:
    image: mysql:8.0
    container_name: portal_db
    env_file:
      - .env
    environment:
      - TZ=${TZ:-Asia/Jakarta}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped
    networks:
      - portal-network
      - portal-login-sec

networks:
  portal-network:
    driver: bridge
  portal-login-sec:
    external: true
    name: portal-login-sec 

volumes:
  mysql_data: